// @ts-nocheck
import { PrismaClient } from "./src/generated/prisma/client.js";

const prisma = new PrismaClient();

async function main() {
  console.log("Seeding database...");

  await prisma.news.deleteMany();
  await prisma.product.deleteMany();
  await prisma.adSpot.deleteMany();
  await prisma.event.deleteMany();

  // NEWS — 6 articles × 4 locales = 24
  const newsRecords = [
    // EN
    { title: "Manchester City Prepares for Champions League Quarter-Final", slug: "city-champions-league-quarter-final", excerpt: "The sky blues gear up for a crucial European clash.", contentBody: "Manchester City are preparing for their Champions League quarter-final match. The team has been training intensively at the Etihad Campus.", featuredImage: "https://images.unsplash.com/photo-1522778119026-d647f0596c20?w=800&h=450&fit=crop", sourceName: "BBC Sport", sourceUrl: "https://bbc.co.uk/sport", publishedAt: new Date("2026-03-14T10:00:00Z"), locale: "en", category: "football" },
    { title: "New Etihad Campus Expansion Announced", slug: "etihad-campus-expansion", excerpt: "A major development project will transform the area surrounding the Etihad Stadium.", contentBody: "City Football Group has announced plans to expand the Etihad Campus with new training facilities.", featuredImage: "https://images.unsplash.com/photo-1577223625816-7546f13df25d?w=800&h=450&fit=crop", sourceName: "Manchester Evening News", sourceUrl: "https://manchestereveningnews.co.uk", publishedAt: new Date("2026-03-13T14:30:00Z"), locale: "en", category: "city" },
    { title: "Manchester's Northern Quarter: A Cultural Renaissance", slug: "northern-quarter-cultural-renaissance", excerpt: "How Manchester's creative heartbeat continues to shape the city's identity.", contentBody: "The Northern Quarter has long been the cultural heart of Manchester.", featuredImage: "https://images.unsplash.com/photo-1515542622106-78bda8ba0e5b?w=800&h=450&fit=crop", sourceName: "The Guardian", sourceUrl: "https://theguardian.com", publishedAt: new Date("2026-03-12T09:15:00Z"), locale: "en", category: "culture" },
    { title: "Premier League Title Race Heats Up", slug: "premier-league-title-race", excerpt: "Every point counts in the most competitive season in years.", contentBody: "The Premier League title race is reaching a fever pitch.", featuredImage: "https://images.unsplash.com/photo-1431324155629-1a6deb1dec8d?w=800&h=450&fit=crop", sourceName: "Sky Sports", sourceUrl: "https://skysports.com", publishedAt: new Date("2026-03-11T16:00:00Z"), locale: "en", category: "football" },
    { title: "Best Matchday Dining Spots Near Etihad Stadium", slug: "matchday-dining-etihad", excerpt: "Where to eat before the big match.", contentBody: "The area around the Etihad Stadium offers fantastic dining options.", featuredImage: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800&h=450&fit=crop", sourceName: "Time Out Manchester", sourceUrl: "https://timeout.com/manchester", publishedAt: new Date("2026-03-10T11:00:00Z"), locale: "en", category: "food" },
    { title: "Youth Academy Star Signs Professional Contract", slug: "youth-academy-star-contract", excerpt: "Another academy product earns their first professional deal.", contentBody: "Manchester City's academy continues to produce top-level talent.", featuredImage: "https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=800&h=450&fit=crop", sourceName: "City Xtra", sourceUrl: "https://cityxtra.com", publishedAt: new Date("2026-03-09T08:45:00Z"), locale: "en", category: "football" },
    // AR
    { title: "مانشستر سيتي يستعد لربع نهائي دوري أبطال أوروبا", slug: "city-champions-league-quarter-final", excerpt: "السماويون يستعدون لمواجهة أوروبية حاسمة.", contentBody: "يستعد مانشستر سيتي لمباراة ربع نهائي دوري أبطال أوروبا.", featuredImage: "https://images.unsplash.com/photo-1522778119026-d647f0596c20?w=800&h=450&fit=crop", sourceName: "بي بي سي سبورت", sourceUrl: "https://bbc.co.uk/sport", publishedAt: new Date("2026-03-14T10:00:00Z"), locale: "ar", category: "football" },
    { title: "الإعلان عن توسعة جديدة لمجمع الاتحاد", slug: "etihad-campus-expansion", excerpt: "مشروع تطوير كبير سيحول المنطقة المحيطة بملعب الاتحاد.", contentBody: "أعلنت مجموعة سيتي فوتبول عن خطط لتوسيع مجمع الاتحاد.", featuredImage: "https://images.unsplash.com/photo-1577223625816-7546f13df25d?w=800&h=450&fit=crop", sourceName: "مانشستر إيفنينغ نيوز", sourceUrl: "https://manchestereveningnews.co.uk", publishedAt: new Date("2026-03-13T14:30:00Z"), locale: "ar", category: "city" },
    { title: "الحي الشمالي في مانشستر: نهضة ثقافية", slug: "northern-quarter-cultural-renaissance", excerpt: "كيف يستمر قلب مانشستر الإبداعي في تشكيل هوية المدينة.", contentBody: "لطالما كان الحي الشمالي القلب الثقافي لمانشستر.", featuredImage: "https://images.unsplash.com/photo-1515542622106-78bda8ba0e5b?w=800&h=450&fit=crop", sourceName: "الغارديان", sourceUrl: "https://theguardian.com", publishedAt: new Date("2026-03-12T09:15:00Z"), locale: "ar", category: "culture" },
    { title: "سباق لقب الدوري الإنجليزي يحتدم", slug: "premier-league-title-race", excerpt: "كل نقطة مهمة في أكثر المواسم تنافسية.", contentBody: "يصل سباق لقب الدوري الإنجليزي الممتاز إلى ذروته.", featuredImage: "https://images.unsplash.com/photo-1431324155629-1a6deb1dec8d?w=800&h=450&fit=crop", sourceName: "سكاي سبورتس", sourceUrl: "https://skysports.com", publishedAt: new Date("2026-03-11T16:00:00Z"), locale: "ar", category: "football" },
    { title: "أفضل أماكن تناول الطعام بالقرب من ملعب الاتحاد", slug: "matchday-dining-etihad", excerpt: "أين تأكل قبل المباراة الكبيرة.", contentBody: "المنطقة المحيطة بملعب الاتحاد توفر خيارات رائعة.", featuredImage: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800&h=450&fit=crop", sourceName: "تايم آوت مانشستر", sourceUrl: "https://timeout.com/manchester", publishedAt: new Date("2026-03-10T11:00:00Z"), locale: "ar", category: "food" },
    { title: "نجم الأكاديمية الشاب يوقع عقداً احترافياً", slug: "youth-academy-star-contract", excerpt: "منتج آخر من نظام الأكاديمية.", contentBody: "تواصل أكاديمية مانشستر سيتي إنتاج مواهب.", featuredImage: "https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=800&h=450&fit=crop", sourceName: "سيتي إكسترا", sourceUrl: "https://cityxtra.com", publishedAt: new Date("2026-03-09T08:45:00Z"), locale: "ar", category: "football" },
    // HE
    { title: "מנצ'סטר סיטי נערכת לרבע גמר ליגת האלופות", slug: "city-champions-league-quarter-final", excerpt: "הכחולים נערכים לעימות אירופי מכריע.", contentBody: "מנצ'סטר סיטי נערכת למשחק רבע הגמר בליגת האלופות.", featuredImage: "https://images.unsplash.com/photo-1522778119026-d647f0596c20?w=800&h=450&fit=crop", sourceName: "BBC Sport", sourceUrl: "https://bbc.co.uk/sport", publishedAt: new Date("2026-03-14T10:00:00Z"), locale: "he", category: "football" },
    { title: "הוכרזה הרחבה חדשה של קמפוס איתיחאד", slug: "etihad-campus-expansion", excerpt: "פרויקט פיתוח גדול ישנה את האזור.", contentBody: "קבוצת סיטי פוטבול הכריזה על תוכניות להרחבת קמפוס איתיחאד.", featuredImage: "https://images.unsplash.com/photo-1577223625816-7546f13df25d?w=800&h=450&fit=crop", sourceName: "Manchester Evening News", sourceUrl: "https://manchestereveningnews.co.uk", publishedAt: new Date("2026-03-13T14:30:00Z"), locale: "he", category: "city" },
    { title: "הרובע הצפוני של מנצ'סטר: רנסנס תרבותי", slug: "northern-quarter-cultural-renaissance", excerpt: "כיצד הלב היצירתי של מנצ'סטר ממשיך לעצב את זהות העיר.", contentBody: "הרובע הצפוני היה מאז ומתמיד הלב התרבותי של מנצ'סטר.", featuredImage: "https://images.unsplash.com/photo-1515542622106-78bda8ba0e5b?w=800&h=450&fit=crop", sourceName: "The Guardian", sourceUrl: "https://theguardian.com", publishedAt: new Date("2026-03-12T09:15:00Z"), locale: "he", category: "culture" },
    { title: "מירוץ האליפות בפרמייר ליג מתחמם", slug: "premier-league-title-race", excerpt: "כל נקודה חשובה בעונה התחרותית ביותר.", contentBody: "מירוץ האליפות בפרמייר ליג מגיע לשיאו.", featuredImage: "https://images.unsplash.com/photo-1431324155629-1a6deb1dec8d?w=800&h=450&fit=crop", sourceName: "Sky Sports", sourceUrl: "https://skysports.com", publishedAt: new Date("2026-03-11T16:00:00Z"), locale: "he", category: "football" },
    { title: "מקומות האוכל הטובים ביותר ליד אצטדיון איתיחאד", slug: "matchday-dining-etihad", excerpt: "איפה לאכול לפני המשחק הגדול.", contentBody: "האזור סביב אצטדיון איתיחאד מציע אפשרויות נהדרות.", featuredImage: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800&h=450&fit=crop", sourceName: "Time Out Manchester", sourceUrl: "https://timeout.com/manchester", publishedAt: new Date("2026-03-10T11:00:00Z"), locale: "he", category: "food" },
    { title: "כוכב האקדמיה הצעיר חותם על חוזה מקצועי", slug: "youth-academy-star-contract", excerpt: "עוד תוצר של מערכת האקדמיה.", contentBody: "האקדמיה של מנצ'סטר סיטי ממשיכה לייצר כישרונות.", featuredImage: "https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=800&h=450&fit=crop", sourceName: "City Xtra", sourceUrl: "https://cityxtra.com", publishedAt: new Date("2026-03-09T08:45:00Z"), locale: "he", category: "football" },
    // ES
    { title: "Manchester City se prepara para los cuartos de final", slug: "city-champions-league-quarter-final", excerpt: "Los celestes se preparan para un enfrentamiento europeo crucial.", contentBody: "El Manchester City se está preparando para su partido de cuartos de final.", featuredImage: "https://images.unsplash.com/photo-1522778119026-d647f0596c20?w=800&h=450&fit=crop", sourceName: "BBC Sport", sourceUrl: "https://bbc.co.uk/sport", publishedAt: new Date("2026-03-14T10:00:00Z"), locale: "es", category: "football" },
    { title: "Anunciada la nueva expansión del Campus Etihad", slug: "etihad-campus-expansion", excerpt: "Un importante proyecto de desarrollo transformará la zona.", contentBody: "City Football Group ha anunciado planes para ampliar el Campus Etihad.", featuredImage: "https://images.unsplash.com/photo-1577223625816-7546f13df25d?w=800&h=450&fit=crop", sourceName: "Manchester Evening News", sourceUrl: "https://manchestereveningnews.co.uk", publishedAt: new Date("2026-03-13T14:30:00Z"), locale: "es", category: "city" },
    { title: "El Northern Quarter: un renacimiento cultural", slug: "northern-quarter-cultural-renaissance", excerpt: "Cómo el corazón creativo de Manchester sigue dando forma a la ciudad.", contentBody: "El Northern Quarter ha sido durante mucho tiempo el corazón cultural de Manchester.", featuredImage: "https://images.unsplash.com/photo-1515542622106-78bda8ba0e5b?w=800&h=450&fit=crop", sourceName: "The Guardian", sourceUrl: "https://theguardian.com", publishedAt: new Date("2026-03-12T09:15:00Z"), locale: "es", category: "culture" },
    { title: "La carrera por el título de la Premier League se intensifica", slug: "premier-league-title-race", excerpt: "Cada punto cuenta en la temporada más competitiva.", contentBody: "La carrera por el título de la Premier League está alcanzando su punto álgido.", featuredImage: "https://images.unsplash.com/photo-1431324155629-1a6deb1dec8d?w=800&h=450&fit=crop", sourceName: "Sky Sports", sourceUrl: "https://skysports.com", publishedAt: new Date("2026-03-11T16:00:00Z"), locale: "es", category: "football" },
    { title: "Los mejores restaurantes cerca del Estadio Etihad", slug: "matchday-dining-etihad", excerpt: "Dónde comer antes del gran partido.", contentBody: "La zona alrededor del Estadio Etihad ofrece opciones fantásticas.", featuredImage: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800&h=450&fit=crop", sourceName: "Time Out Manchester", sourceUrl: "https://timeout.com/manchester", publishedAt: new Date("2026-03-10T11:00:00Z"), locale: "es", category: "food" },
    { title: "Estrella juvenil firma contrato profesional", slug: "youth-academy-star-contract", excerpt: "Otro producto de la academia de clase mundial.", contentBody: "La academia del Manchester City sigue produciendo talento.", featuredImage: "https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=800&h=450&fit=crop", sourceName: "City Xtra", sourceUrl: "https://cityxtra.com", publishedAt: new Date("2026-03-09T08:45:00Z"), locale: "es", category: "football" },
  ];
  await prisma.news.createMany({ data: newsRecords });
  console.log("News:", newsRecords.length);

  // PRODUCTS — 4 per locale × 4 = 16
  const productRecords = [
    { productName: "Manchester Skyline Premium Print", productSlug: "manchester-skyline-print", productImage: "https://images.unsplash.com/photo-1605034313761-73ea4a0cfbf3?w=400&h=400&fit=crop", descriptionShort: "Stunning high-quality print of the Manchester skyline.", priceDisplay: "£29.99", priceAmount: 29.99, affiliateLink: "#", partnerName: "Amazon UK", locale: "en", category: "art" },
    { productName: "Sky Blue Heritage Scarf", productSlug: "sky-blue-heritage-scarf", productImage: "https://images.unsplash.com/photo-1520903920243-00d872a2d1c9?w=400&h=400&fit=crop", descriptionShort: "Classic sky blue and white scarf.", priceDisplay: "£19.99", priceAmount: 19.99, affiliateLink: "#", partnerName: "Fanatics", locale: "en", category: "apparel" },
    { productName: "Manchester City Guide Book", productSlug: "city-guide-book", productImage: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400&h=400&fit=crop", descriptionShort: "The definitive guide to Manchester.", priceDisplay: "£14.99", priceAmount: 14.99, affiliateLink: "#", partnerName: "Amazon UK", locale: "en", category: "books" },
    { productName: "Football Culture Magazine", productSlug: "football-culture-magazine", productImage: "https://images.unsplash.com/photo-1526666923127-b2970f64b422?w=400&h=400&fit=crop", descriptionShort: "Monthly magazine covering football culture.", priceDisplay: "£9.99/mo", priceAmount: 9.99, affiliateLink: "#", partnerName: "Press Partner", locale: "en", category: "magazines" },
    { productName: "طباعة أفق مانشستر الفاخرة", productSlug: "manchester-skyline-print", productImage: "https://images.unsplash.com/photo-1605034313761-73ea4a0cfbf3?w=400&h=400&fit=crop", descriptionShort: "طباعة عالية الجودة لأفق مانشستر.", priceDisplay: "£29.99", priceAmount: 29.99, affiliateLink: "#", partnerName: "Amazon UK", locale: "ar", category: "art" },
    { productName: "وشاح التراث الأزرق السماوي", productSlug: "sky-blue-heritage-scarf", productImage: "https://images.unsplash.com/photo-1520903920243-00d872a2d1c9?w=400&h=400&fit=crop", descriptionShort: "وشاح كلاسيكي باللون الأزرق السماوي.", priceDisplay: "£19.99", priceAmount: 19.99, affiliateLink: "#", partnerName: "Fanatics", locale: "ar", category: "apparel" },
    { productName: "كتاب دليل مانشستر", productSlug: "city-guide-book", productImage: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400&h=400&fit=crop", descriptionShort: "الدليل الشامل لمانشستر.", priceDisplay: "£14.99", priceAmount: 14.99, affiliateLink: "#", partnerName: "Amazon UK", locale: "ar", category: "books" },
    { productName: "مجلة ثقافة كرة القدم", productSlug: "football-culture-magazine", productImage: "https://images.unsplash.com/photo-1526666923127-b2970f64b422?w=400&h=400&fit=crop", descriptionShort: "مجلة شهرية تغطي ثقافة كرة القدم.", priceDisplay: "£9.99/شهرياً", priceAmount: 9.99, affiliateLink: "#", partnerName: "Press Partner", locale: "ar", category: "magazines" },
    { productName: "הדפס פרימיום של קו הרקיע של מנצ'סטר", productSlug: "manchester-skyline-print", productImage: "https://images.unsplash.com/photo-1605034313761-73ea4a0cfbf3?w=400&h=400&fit=crop", descriptionShort: "הדפס איכותי מדהים של קו הרקיע של מנצ'סטר.", priceDisplay: "£29.99", priceAmount: 29.99, affiliateLink: "#", partnerName: "Amazon UK", locale: "he", category: "art" },
    { productName: "צעיף מורשת כחול שמיים", productSlug: "sky-blue-heritage-scarf", productImage: "https://images.unsplash.com/photo-1520903920243-00d872a2d1c9?w=400&h=400&fit=crop", descriptionShort: "צעיף קלאסי בכחול שמיים ולבן.", priceDisplay: "£19.99", priceAmount: 19.99, affiliateLink: "#", partnerName: "Fanatics", locale: "he", category: "apparel" },
    { productName: "ספר מדריך מנצ'סטר", productSlug: "city-guide-book", productImage: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400&h=400&fit=crop", descriptionShort: "המדריך המוחלט למנצ'סטר.", priceDisplay: "£14.99", priceAmount: 14.99, affiliateLink: "#", partnerName: "Amazon UK", locale: "he", category: "books" },
    { productName: "מגזין תרבות כדורגל", productSlug: "football-culture-magazine", productImage: "https://images.unsplash.com/photo-1526666923127-b2970f64b422?w=400&h=400&fit=crop", descriptionShort: "מגזין חודשי המכסה תרבות כדורגל.", priceDisplay: "£9.99/חודש", priceAmount: 9.99, affiliateLink: "#", partnerName: "Press Partner", locale: "he", category: "magazines" },
    { productName: "Impresión Premium del Horizonte de Manchester", productSlug: "manchester-skyline-print", productImage: "https://images.unsplash.com/photo-1605034313761-73ea4a0cfbf3?w=400&h=400&fit=crop", descriptionShort: "Impresión de alta calidad del horizonte de Manchester.", priceDisplay: "£29.99", priceAmount: 29.99, affiliateLink: "#", partnerName: "Amazon UK", locale: "es", category: "art" },
    { productName: "Bufanda Heritage Azul Cielo", productSlug: "sky-blue-heritage-scarf", productImage: "https://images.unsplash.com/photo-1520903920243-00d872a2d1c9?w=400&h=400&fit=crop", descriptionShort: "Bufanda clásica en azul cielo y blanco.", priceDisplay: "£19.99", priceAmount: 19.99, affiliateLink: "#", partnerName: "Fanatics", locale: "es", category: "apparel" },
    { productName: "Libro Guía de Manchester", productSlug: "city-guide-book", productImage: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400&h=400&fit=crop", descriptionShort: "La guía definitiva de Manchester.", priceDisplay: "£14.99", priceAmount: 14.99, affiliateLink: "#", partnerName: "Amazon UK", locale: "es", category: "books" },
    { productName: "Revista Cultura del Fútbol", productSlug: "football-culture-magazine", productImage: "https://images.unsplash.com/photo-1526666923127-b2970f64b422?w=400&h=400&fit=crop", descriptionShort: "Revista mensual sobre cultura futbolística.", priceDisplay: "£9.99/mes", priceAmount: 9.99, affiliateLink: "#", partnerName: "Press Partner", locale: "es", category: "magazines" },
  ];
  await prisma.product.createMany({ data: productRecords });
  console.log("Products:", productRecords.length);

  // ADS
  await prisma.adSpot.createMany({ data: [
    { spotName: "header-banner", adType: "image", adImageUrl: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1200&h=120&fit=crop", clickUrl: "#", locale: "en", isActive: true },
    { spotName: "content-inline", adType: "image", adImageUrl: "https://images.unsplash.com/photo-1449824913935-59a10b8d2000?w=800&h=200&fit=crop", clickUrl: "#", locale: "en", isActive: true },
  ]});
  console.log("Ads: 2");

  // EVENTS
  const eventRecords = [
    { title: "Manchester City vs Arsenal", slug: "city-vs-arsenal-pl", description: "A crucial Premier League clash at the Etihad Stadium.", eventImage: "https://images.unsplash.com/photo-1522778119026-d647f0596c20?w=800&h=450&fit=crop", venue: "Etihad Stadium", eventDate: new Date("2026-04-05T15:00:00Z"), ticketUrl: "https://mancity.com/tickets", priceRange: "£45-£120", category: "sport", locale: "en", isFeatured: true },
    { title: "Manchester International Festival 2026", slug: "manchester-international-festival-2026", description: "The city's premier arts and culture festival.", eventImage: "https://images.unsplash.com/photo-1501281668745-f7f57925c3b4?w=800&h=450&fit=crop", venue: "Various Venues", eventDate: new Date("2026-06-15T10:00:00Z"), eventEnd: new Date("2026-07-06T23:00:00Z"), priceRange: "Free-£50", category: "culture", locale: "en", isFeatured: true },
    { title: "Etihad Stadium Tour", slug: "etihad-stadium-tour", description: "Go behind the scenes of the Etihad Stadium.", eventImage: "https://images.unsplash.com/photo-1577223625816-7546f13df25d?w=800&h=450&fit=crop", venue: "Etihad Stadium", eventDate: new Date("2026-03-20T10:00:00Z"), ticketUrl: "https://mancity.com/tours", priceRange: "£25", category: "sport", locale: "en", isFeatured: true },
    { title: "Manchester Food & Drink Festival", slug: "food-drink-festival-2026", description: "Celebrating Manchester's incredible food scene.", eventImage: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800&h=450&fit=crop", venue: "Albert Square", eventDate: new Date("2026-05-10T12:00:00Z"), eventEnd: new Date("2026-05-20T22:00:00Z"), priceRange: "Free", category: "food", locale: "en", isFeatured: true },
    // AR events
    { title: "مانشستر سيتي ضد آرسنال", slug: "city-vs-arsenal-pl", description: "مواجهة حاسمة في الدوري الإنجليزي.", eventImage: "https://images.unsplash.com/photo-1522778119026-d647f0596c20?w=800&h=450&fit=crop", venue: "ملعب الاتحاد", eventDate: new Date("2026-04-05T15:00:00Z"), ticketUrl: "https://mancity.com/tickets", priceRange: "£45-£120", category: "sport", locale: "ar", isFeatured: true },
    { title: "جولة ملعب الاتحاد", slug: "etihad-stadium-tour", description: "اذهب وراء الكواليس.", eventImage: "https://images.unsplash.com/photo-1577223625816-7546f13df25d?w=800&h=450&fit=crop", venue: "ملعب الاتحاد", eventDate: new Date("2026-03-20T10:00:00Z"), ticketUrl: "https://mancity.com/tours", priceRange: "£25", category: "sport", locale: "ar", isFeatured: true },
    // HE events
    { title: "מנצ'סטר סיטי נגד ארסנל", slug: "city-vs-arsenal-pl", description: "עימות מכריע בפרמייר ליג.", eventImage: "https://images.unsplash.com/photo-1522778119026-d647f0596c20?w=800&h=450&fit=crop", venue: "אצטדיון איתיחאד", eventDate: new Date("2026-04-05T15:00:00Z"), ticketUrl: "https://mancity.com/tickets", priceRange: "£45-£120", category: "sport", locale: "he", isFeatured: true },
    { title: "סיור באצטדיון איתיחאד", slug: "etihad-stadium-tour", description: "היכנסו מאחורי הקלעים.", eventImage: "https://images.unsplash.com/photo-1577223625816-7546f13df25d?w=800&h=450&fit=crop", venue: "אצטדיון איתיחאד", eventDate: new Date("2026-03-20T10:00:00Z"), ticketUrl: "https://mancity.com/tours", priceRange: "£25", category: "sport", locale: "he", isFeatured: true },
    // ES events
    { title: "Manchester City vs Arsenal", slug: "city-vs-arsenal-pl", description: "Un choque crucial de la Premier League.", eventImage: "https://images.unsplash.com/photo-1522778119026-d647f0596c20?w=800&h=450&fit=crop", venue: "Estadio Etihad", eventDate: new Date("2026-04-05T15:00:00Z"), ticketUrl: "https://mancity.com/tickets", priceRange: "£45-£120", category: "sport", locale: "es", isFeatured: true },
    { title: "Tour del Estadio Etihad", slug: "etihad-stadium-tour", description: "Ve detrás de escena en el Estadio Etihad.", eventImage: "https://images.unsplash.com/photo-1577223625816-7546f13df25d?w=800&h=450&fit=crop", venue: "Estadio Etihad", eventDate: new Date("2026-03-20T10:00:00Z"), ticketUrl: "https://mancity.com/tours", priceRange: "£25", category: "sport", locale: "es", isFeatured: true },
  ];
  await prisma.event.createMany({ data: eventRecords });
  console.log("Events:", eventRecords.length);

  console.log("Seed complete!");
}

main()
  .catch((e) => { console.error(e); process.exit(1); })
  .finally(async () => { await prisma.$disconnect(); });
