// @ts-nocheck
import { PrismaClient } from "../src/generated/prisma";

const prisma = new PrismaClient();

async function main() {
  console.log("🌱 Seeding database...");

  // Clear existing data
  await prisma.news.deleteMany();
  await prisma.product.deleteMany();
  await prisma.adSpot.deleteMany();
  await prisma.event.deleteMany();

  // ============================================================
  // NEWS
  // ============================================================
  const newsRecords = [
    // --- EN ---
    { title: "Manchester City Prepares for Champions League Quarter-Final", slug: "city-champions-league-quarter-final", excerpt: "The sky blues gear up for a crucial European clash as they aim to defend their title.", contentBody: "Manchester City are preparing for their Champions League quarter-final match. The team has been training intensively at the Etihad Campus, with key players returning from injury. Manager Pep Guardiola has expressed confidence in his squad's depth and quality, highlighting the importance of every player in the rotation. The Champions League represents the pinnacle of European club football, and City's ambition to retain the trophy has galvanized the entire squad.", featuredImage: "https://images.unsplash.com/photo-1522778119026-d647f0596c20?w=800&h=450&fit=crop", sourceName: "BBC Sport", sourceUrl: "https://bbc.co.uk/sport", publishedAt: new Date("2026-03-14T10:00:00Z"), locale: "en", category: "football" },
    { title: "New Etihad Campus Expansion Announced", slug: "etihad-campus-expansion", excerpt: "A major development project will transform the area surrounding the Etihad Stadium.", contentBody: "City Football Group has announced plans to expand the Etihad Campus with new training facilities, community spaces, and a state-of-the-art sports science center. The project, valued at over £300 million, will create thousands of local jobs and further establish Manchester as a global sporting hub.", featuredImage: "https://images.unsplash.com/photo-1577223625816-7546f13df25d?w=800&h=450&fit=crop", sourceName: "Manchester Evening News", sourceUrl: "https://manchestereveningnews.co.uk", publishedAt: new Date("2026-03-13T14:30:00Z"), locale: "en", category: "city" },
    { title: "Manchester's Northern Quarter: A Cultural Renaissance", slug: "northern-quarter-cultural-renaissance", excerpt: "How Manchester's creative heartbeat continues to shape the city's identity.", contentBody: "The Northern Quarter has long been the cultural heart of Manchester, with its independent shops, street art, and vibrant nightlife scene. Recently, new galleries and creative spaces have opened, attracting artists and entrepreneurs from across the globe. The area's unique character, blending Victorian architecture with contemporary creativity, makes it a must-visit destination.", featuredImage: "https://images.unsplash.com/photo-1515542622106-78bda8ba0e5b?w=800&h=450&fit=crop", sourceName: "The Guardian", sourceUrl: "https://theguardian.com", publishedAt: new Date("2026-03-12T09:15:00Z"), locale: "en", category: "culture" },
    { title: "Premier League Title Race Heats Up", slug: "premier-league-title-race", excerpt: "With just weeks remaining, every point counts in the most competitive season in years.", contentBody: "The Premier League title race is reaching a fever pitch as teams battle for the coveted trophy. Manchester City remain in strong contention, with their formidable squad depth and tactical excellence under Guardiola proving decisive in key fixtures.", featuredImage: "https://images.unsplash.com/photo-1431324155629-1a6deb1dec8d?w=800&h=450&fit=crop", sourceName: "Sky Sports", sourceUrl: "https://skysports.com", publishedAt: new Date("2026-03-11T16:00:00Z"), locale: "en", category: "football" },
    { title: "Best Matchday Dining Spots Near Etihad Stadium", slug: "matchday-dining-etihad", excerpt: "From local favourites to hidden gems — where to eat before the big match.", contentBody: "Whether you're looking for a quick bite or a proper sit-down meal before the game, the area around the Etihad Stadium offers fantastic options. From award-winning curry houses on the famous Curry Mile to trendy brunch spots in Ancoats, Manchester's food scene delivers on matchday and beyond.", featuredImage: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800&h=450&fit=crop", sourceName: "Time Out Manchester", sourceUrl: "https://timeout.com/manchester", publishedAt: new Date("2026-03-10T11:00:00Z"), locale: "en", category: "food" },
    { title: "Youth Academy Star Signs Professional Contract", slug: "youth-academy-star-contract", excerpt: "Another product of the world-class academy system earns their first professional deal.", contentBody: "Manchester City's academy continues to produce top-level talent with another graduate signing a professional contract. The club's investment in youth development has been a cornerstone of their long-term strategy, producing players who understand the club's philosophy from an early age.", featuredImage: "https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=800&h=450&fit=crop", sourceName: "City Xtra", sourceUrl: "https://cityxtra.com", publishedAt: new Date("2026-03-09T08:45:00Z"), locale: "en", category: "football" },

    // --- AR ---
    { title: "مانشستر سيتي يستعد لربع نهائي دوري أبطال أوروبا", slug: "city-champions-league-quarter-final", excerpt: "السماويون يستعدون لمواجهة أوروبية حاسمة في سعيهم للدفاع عن لقبهم.", contentBody: "يستعد مانشستر سيتي لمباراة ربع نهائي دوري أبطال أوروبا. وقد كان الفريق يتدرب بشكل مكثف في أكاديمية الاتحاد مع عودة اللاعبين الرئيسيين من الإصابة. أعرب المدرب بيب غوارديولا عن ثقته بعمق تشكيلته وجودتها.", featuredImage: "https://images.unsplash.com/photo-1522778119026-d647f0596c20?w=800&h=450&fit=crop", sourceName: "بي بي سي سبورت", sourceUrl: "https://bbc.co.uk/sport", publishedAt: new Date("2026-03-14T10:00:00Z"), locale: "ar", category: "football" },
    { title: "الإعلان عن توسعة جديدة لمجمع الاتحاد", slug: "etihad-campus-expansion", excerpt: "مشروع تطوير كبير سيحول المنطقة المحيطة بملعب الاتحاد.", contentBody: "أعلنت مجموعة سيتي فوتبول عن خطط لتوسيع مجمع الاتحاد بمرافق تدريب جديدة ومساحات مجتمعية ومركز متطور لعلوم الرياضة.", featuredImage: "https://images.unsplash.com/photo-1577223625816-7546f13df25d?w=800&h=450&fit=crop", sourceName: "مانشستر إيفنينغ نيوز", sourceUrl: "https://manchestereveningnews.co.uk", publishedAt: new Date("2026-03-13T14:30:00Z"), locale: "ar", category: "city" },
    { title: "الحي الشمالي في مانشستر: نهضة ثقافية", slug: "northern-quarter-cultural-renaissance", excerpt: "كيف يستمر قلب مانشستر الإبداعي في تشكيل هوية المدينة.", contentBody: "لطالما كان الحي الشمالي القلب الثقافي لمانشستر بمحلاته المستقلة وفنون الشارع والحياة الليلية النابضة بالحياة.", featuredImage: "https://images.unsplash.com/photo-1515542622106-78bda8ba0e5b?w=800&h=450&fit=crop", sourceName: "الغارديان", sourceUrl: "https://theguardian.com", publishedAt: new Date("2026-03-12T09:15:00Z"), locale: "ar", category: "culture" },
    { title: "سباق لقب الدوري الإنجليزي يحتدم", slug: "premier-league-title-race", excerpt: "مع بقاء أسابيع قليلة، كل نقطة مهمة في أكثر المواسم تنافسية منذ سنوات.", contentBody: "يصل سباق لقب الدوري الإنجليزي الممتاز إلى ذروته مع تنافس الفرق على الكأس المرغوبة.", featuredImage: "https://images.unsplash.com/photo-1431324155629-1a6deb1dec8d?w=800&h=450&fit=crop", sourceName: "سكاي سبورتس", sourceUrl: "https://skysports.com", publishedAt: new Date("2026-03-11T16:00:00Z"), locale: "ar", category: "football" },
    { title: "أفضل أماكن تناول الطعام بالقرب من ملعب الاتحاد", slug: "matchday-dining-etihad", excerpt: "من المفضلات المحلية إلى الجواهر المخفية — أين تأكل قبل المباراة الكبيرة.", contentBody: "سواء كنت تبحث عن وجبة سريعة أو عشاء مناسب قبل المباراة، المنطقة المحيطة بملعب الاتحاد توفر خيارات رائعة.", featuredImage: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800&h=450&fit=crop", sourceName: "تايم آوت مانشستر", sourceUrl: "https://timeout.com/manchester", publishedAt: new Date("2026-03-10T11:00:00Z"), locale: "ar", category: "food" },
    { title: "نجم الأكاديمية الشاب يوقع عقداً احترافياً", slug: "youth-academy-star-contract", excerpt: "منتج آخر من نظام الأكاديمية العالمي يحصل على أول عقد احترافي له.", contentBody: "تواصل أكاديمية مانشستر سيتي إنتاج مواهب من الدرجة الأولى مع توقيع خريج آخر لعقد احترافي.", featuredImage: "https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=800&h=450&fit=crop", sourceName: "سيتي إكسترا", sourceUrl: "https://cityxtra.com", publishedAt: new Date("2026-03-09T08:45:00Z"), locale: "ar", category: "football" },

    // --- HE ---
    { title: "מנצ'סטר סיטי נערכת לרבע גמר ליגת האלופות", slug: "city-champions-league-quarter-final", excerpt: "הכחולים נערכים לעימות אירופי מכריע במטרה להגן על התואר שלהם.", contentBody: "מנצ'סטר סיטי נערכת למשחק רבע הגמר בליגת האלופות. הקבוצה התאמנה באינטנסיביות בקמפוס איתיחאד עם שחקני מפתח שחזרו מפציעה.", featuredImage: "https://images.unsplash.com/photo-1522778119026-d647f0596c20?w=800&h=450&fit=crop", sourceName: "BBC Sport", sourceUrl: "https://bbc.co.uk/sport", publishedAt: new Date("2026-03-14T10:00:00Z"), locale: "he", category: "football" },
    { title: "הוכרזה הרחבה חדשה של קמפוס איתיחאד", slug: "etihad-campus-expansion", excerpt: "פרויקט פיתוח גדול ישנה את האזור שמסביב לאצטדיון איתיחאד.", contentBody: "קבוצת סיטי פוטבול הכריזה על תוכניות להרחבת קמפוס איתיחאד עם מתקני אימון חדשים ומרחבים קהילתיים.", featuredImage: "https://images.unsplash.com/photo-1577223625816-7546f13df25d?w=800&h=450&fit=crop", sourceName: "Manchester Evening News", sourceUrl: "https://manchestereveningnews.co.uk", publishedAt: new Date("2026-03-13T14:30:00Z"), locale: "he", category: "city" },
    { title: "הרובע הצפוני של מנצ'סטר: רנסנס תרבותי", slug: "northern-quarter-cultural-renaissance", excerpt: "כיצד הלב היצירתי של מנצ'סטר ממשיך לעצב את זהות העיר.", contentBody: "הרובע הצפוני היה מאז ומתמיד הלב התרבותי של מנצ'סטר עם חנויות עצמאיות, אמנות רחוב וחיי לילה תוססים.", featuredImage: "https://images.unsplash.com/photo-1515542622106-78bda8ba0e5b?w=800&h=450&fit=crop", sourceName: "The Guardian", sourceUrl: "https://theguardian.com", publishedAt: new Date("2026-03-12T09:15:00Z"), locale: "he", category: "culture" },
    { title: "מירוץ האליפות בפרמייר ליג מתחמם", slug: "premier-league-title-race", excerpt: "עם שבועות ספורים שנותרו, כל נקודה חשובה בעונה התחרותית ביותר מזה שנים.", contentBody: "מירוץ האליפות בפרמייר ליג מגיע לשיאו כאשר קבוצות נלחמות על הגביע.", featuredImage: "https://images.unsplash.com/photo-1431324155629-1a6deb1dec8d?w=800&h=450&fit=crop", sourceName: "Sky Sports", sourceUrl: "https://skysports.com", publishedAt: new Date("2026-03-11T16:00:00Z"), locale: "he", category: "football" },
    { title: "מקומות האוכל הטובים ביותר ליד אצטדיון איתיחאד", slug: "matchday-dining-etihad", excerpt: "מהמועדפים המקומיים ועד לפנינים נסתרות — איפה לאכול לפני המשחק הגדול.", contentBody: "בין אם אתם מחפשים ביס מהיר או ארוחה מסודרת לפני המשחק, האזור סביב אצטדיון איתיחאד מציע אפשרויות נהדרות.", featuredImage: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800&h=450&fit=crop", sourceName: "Time Out Manchester", sourceUrl: "https://timeout.com/manchester", publishedAt: new Date("2026-03-10T11:00:00Z"), locale: "he", category: "food" },
    { title: "כוכב האקדמיה הצעיר חותם על חוזה מקצועי", slug: "youth-academy-star-contract", excerpt: "עוד תוצר של מערכת האקדמיה ברמה עולמית מרוויח את החוזה המקצועי הראשון שלו.", contentBody: "האקדמיה של מנצ'סטר סיטי ממשיכה לייצר כישרונות ברמה הגבוהה ביותר עם עוד בוגר שחותם על חוזה מקצועי.", featuredImage: "https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=800&h=450&fit=crop", sourceName: "City Xtra", sourceUrl: "https://cityxtra.com", publishedAt: new Date("2026-03-09T08:45:00Z"), locale: "he", category: "football" },

    // --- ES ---
    { title: "Manchester City se prepara para los cuartos de final de la Champions League", slug: "city-champions-league-quarter-final", excerpt: "Los celestes se preparan para un enfrentamiento europeo crucial en su defensa del título.", contentBody: "El Manchester City se está preparando para su partido de cuartos de final de la Liga de Campeones. El equipo ha estado entrenando intensamente en el Campus Etihad con jugadores clave regresando de lesiones.", featuredImage: "https://images.unsplash.com/photo-1522778119026-d647f0596c20?w=800&h=450&fit=crop", sourceName: "BBC Sport", sourceUrl: "https://bbc.co.uk/sport", publishedAt: new Date("2026-03-14T10:00:00Z"), locale: "es", category: "football" },
    { title: "Anunciada la nueva expansión del Campus Etihad", slug: "etihad-campus-expansion", excerpt: "Un importante proyecto de desarrollo transformará la zona que rodea el Estadio Etihad.", contentBody: "City Football Group ha anunciado planes para ampliar el Campus Etihad con nuevas instalaciones de entrenamiento y espacios comunitarios.", featuredImage: "https://images.unsplash.com/photo-1577223625816-7546f13df25d?w=800&h=450&fit=crop", sourceName: "Manchester Evening News", sourceUrl: "https://manchestereveningnews.co.uk", publishedAt: new Date("2026-03-13T14:30:00Z"), locale: "es", category: "city" },
    { title: "El Northern Quarter de Manchester: un renacimiento cultural", slug: "northern-quarter-cultural-renaissance", excerpt: "Cómo el corazón creativo de Manchester sigue dando forma a la identidad de la ciudad.", contentBody: "El Northern Quarter ha sido durante mucho tiempo el corazón cultural de Manchester con sus tiendas independientes, arte callejero y vibrante vida nocturna.", featuredImage: "https://images.unsplash.com/photo-1515542622106-78bda8ba0e5b?w=800&h=450&fit=crop", sourceName: "The Guardian", sourceUrl: "https://theguardian.com", publishedAt: new Date("2026-03-12T09:15:00Z"), locale: "es", category: "culture" },
    { title: "La carrera por el título de la Premier League se intensifica", slug: "premier-league-title-race", excerpt: "Con pocas semanas restantes, cada punto cuenta en la temporada más competitiva en años.", contentBody: "La carrera por el título de la Premier League está alcanzando su punto álgido mientras los equipos luchan por el codiciado trofeo.", featuredImage: "https://images.unsplash.com/photo-1431324155629-1a6deb1dec8d?w=800&h=450&fit=crop", sourceName: "Sky Sports", sourceUrl: "https://skysports.com", publishedAt: new Date("2026-03-11T16:00:00Z"), locale: "es", category: "football" },
    { title: "Los mejores restaurantes cerca del Estadio Etihad", slug: "matchday-dining-etihad", excerpt: "Desde los favoritos locales hasta joyas ocultas: dónde comer antes del gran partido.", contentBody: "Ya sea que busques un bocado rápido o una comida adecuada antes del partido, la zona alrededor del Estadio Etihad ofrece opciones fantásticas.", featuredImage: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800&h=450&fit=crop", sourceName: "Time Out Manchester", sourceUrl: "https://timeout.com/manchester", publishedAt: new Date("2026-03-10T11:00:00Z"), locale: "es", category: "food" },
    { title: "Estrella juvenil firma contrato profesional", slug: "youth-academy-star-contract", excerpt: "Otro producto del sistema de academia de clase mundial consigue su primer contrato profesional.", contentBody: "La academia del Manchester City sigue produciendo talento de primer nivel con otro graduado firmando un contrato profesional.", featuredImage: "https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=800&h=450&fit=crop", sourceName: "City Xtra", sourceUrl: "https://cityxtra.com", publishedAt: new Date("2026-03-09T08:45:00Z"), locale: "es", category: "football" },
  ];

  await prisma.news.createMany({ data: newsRecords });
  console.log(`✅ ${newsRecords.length} news articles created`);

  // ============================================================
  // PRODUCTS
  // ============================================================
  const productRecords = [
    // --- EN ---
    { productName: "Manchester Skyline Premium Print", productSlug: "manchester-skyline-print", productImage: "https://images.unsplash.com/photo-1605034313761-73ea4a0cfbf3?w=400&h=400&fit=crop", descriptionShort: "Stunning high-quality print of the Manchester skyline. Perfect for any fan's wall.", priceDisplay: "£29.99", priceAmount: 29.99, affiliateLink: "#", partnerName: "Amazon UK", locale: "en", category: "art" },
    { productName: "Sky Blue Heritage Scarf", productSlug: "sky-blue-heritage-scarf", productImage: "https://images.unsplash.com/photo-1520903920243-00d872a2d1c9?w=400&h=400&fit=crop", descriptionShort: "Classic sky blue and white scarf. Show your city colours with pride.", priceDisplay: "£19.99", priceAmount: 19.99, affiliateLink: "#", partnerName: "Fanatics", locale: "en", category: "apparel" },
    { productName: "Manchester City Guide Book", productSlug: "city-guide-book", productImage: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400&h=400&fit=crop", descriptionShort: "The definitive guide to Manchester — culture, food, history, and football.", priceDisplay: "£14.99", priceAmount: 14.99, affiliateLink: "#", partnerName: "Amazon UK", locale: "en", category: "books" },
    { productName: "Football Culture Magazine", productSlug: "football-culture-magazine", productImage: "https://images.unsplash.com/photo-1526666923127-b2970f64b422?w=400&h=400&fit=crop", descriptionShort: "Monthly magazine covering football culture, fashion, and fan stories.", priceDisplay: "£9.99/mo", priceAmount: 9.99, affiliateLink: "#", partnerName: "Press Partner", locale: "en", category: "magazines" },

    // --- AR ---
    { productName: "طباعة أفق مانشستر الفاخرة", productSlug: "manchester-skyline-print", productImage: "https://images.unsplash.com/photo-1605034313761-73ea4a0cfbf3?w=400&h=400&fit=crop", descriptionShort: "طباعة عالية الجودة لأفق مانشستر. مثالية لجدار أي مشجع.", priceDisplay: "£29.99", priceAmount: 29.99, affiliateLink: "#", partnerName: "Amazon UK", locale: "ar", category: "art" },
    { productName: "وشاح التراث الأزرق السماوي", productSlug: "sky-blue-heritage-scarf", productImage: "https://images.unsplash.com/photo-1520903920243-00d872a2d1c9?w=400&h=400&fit=crop", descriptionShort: "وشاح كلاسيكي باللون الأزرق السماوي والأبيض. أظهر ألوان مدينتك بفخر.", priceDisplay: "£19.99", priceAmount: 19.99, affiliateLink: "#", partnerName: "Fanatics", locale: "ar", category: "apparel" },
    { productName: "كتاب دليل مانشستر", productSlug: "city-guide-book", productImage: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400&h=400&fit=crop", descriptionShort: "الدليل الشامل لمانشستر — الثقافة والطعام والتاريخ وكرة القدم.", priceDisplay: "£14.99", priceAmount: 14.99, affiliateLink: "#", partnerName: "Amazon UK", locale: "ar", category: "books" },
    { productName: "مجلة ثقافة كرة القدم", productSlug: "football-culture-magazine", productImage: "https://images.unsplash.com/photo-1526666923127-b2970f64b422?w=400&h=400&fit=crop", descriptionShort: "مجلة شهرية تغطي ثقافة كرة القدم والأزياء وقصص المشجعين.", priceDisplay: "£9.99/شهرياً", priceAmount: 9.99, affiliateLink: "#", partnerName: "Press Partner", locale: "ar", category: "magazines" },

    // --- HE ---
    { productName: "הדפס פרימיום של קו הרקיע של מנצ'סטר", productSlug: "manchester-skyline-print", productImage: "https://images.unsplash.com/photo-1605034313761-73ea4a0cfbf3?w=400&h=400&fit=crop", descriptionShort: "הדפס איכותי מדהים של קו הרקיע של מנצ'סטר. מושלם לקיר של כל אוהד.", priceDisplay: "£29.99", priceAmount: 29.99, affiliateLink: "#", partnerName: "Amazon UK", locale: "he", category: "art" },
    { productName: "צעיף מורשת כחול שמיים", productSlug: "sky-blue-heritage-scarf", productImage: "https://images.unsplash.com/photo-1520903920243-00d872a2d1c9?w=400&h=400&fit=crop", descriptionShort: "צעיף קלאסי בכחול שמיים ולבן. הציגו את צבעי העיר שלכם בגאווה.", priceDisplay: "£19.99", priceAmount: 19.99, affiliateLink: "#", partnerName: "Fanatics", locale: "he", category: "apparel" },
    { productName: "ספר מדריך מנצ'סטר", productSlug: "city-guide-book", productImage: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400&h=400&fit=crop", descriptionShort: "המדריך המוחלט למנצ'סטר — תרבות, אוכל, היסטוריה וכדורגל.", priceDisplay: "£14.99", priceAmount: 14.99, affiliateLink: "#", partnerName: "Amazon UK", locale: "he", category: "books" },
    { productName: "מגזין תרבות כדורגל", productSlug: "football-culture-magazine", productImage: "https://images.unsplash.com/photo-1526666923127-b2970f64b422?w=400&h=400&fit=crop", descriptionShort: "מגזין חודשי המכסה תרבות כדורגל, אופנה וסיפורי אוהדים.", priceDisplay: "£9.99/חודש", priceAmount: 9.99, affiliateLink: "#", partnerName: "Press Partner", locale: "he", category: "magazines" },

    // --- ES ---
    { productName: "Impresión Premium del Horizonte de Manchester", productSlug: "manchester-skyline-print", productImage: "https://images.unsplash.com/photo-1605034313761-73ea4a0cfbf3?w=400&h=400&fit=crop", descriptionShort: "Impresión de alta calidad del horizonte de Manchester. Perfecta para cualquier aficionado.", priceDisplay: "£29.99", priceAmount: 29.99, affiliateLink: "#", partnerName: "Amazon UK", locale: "es", category: "art" },
    { productName: "Bufanda Heritage Azul Cielo", productSlug: "sky-blue-heritage-scarf", productImage: "https://images.unsplash.com/photo-1520903920243-00d872a2d1c9?w=400&h=400&fit=crop", descriptionShort: "Bufanda clásica en azul cielo y blanco. Muestra los colores de tu ciudad con orgullo.", priceDisplay: "£19.99", priceAmount: 19.99, affiliateLink: "#", partnerName: "Fanatics", locale: "es", category: "apparel" },
    { productName: "Libro Guía de Manchester", productSlug: "city-guide-book", productImage: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400&h=400&fit=crop", descriptionShort: "La guía definitiva de Manchester: cultura, gastronomía, historia y fútbol.", priceDisplay: "£14.99", priceAmount: 14.99, affiliateLink: "#", partnerName: "Amazon UK", locale: "es", category: "books" },
    { productName: "Revista Cultura del Fútbol", productSlug: "football-culture-magazine", productImage: "https://images.unsplash.com/photo-1526666923127-b2970f64b422?w=400&h=400&fit=crop", descriptionShort: "Revista mensual sobre cultura futbolística, moda e historias de aficionados.", priceDisplay: "£9.99/mes", priceAmount: 9.99, affiliateLink: "#", partnerName: "Press Partner", locale: "es", category: "magazines" },
  ];

  await prisma.product.createMany({ data: productRecords });
  console.log(`✅ ${productRecords.length} products created`);

  // ============================================================
  // ADS
  // ============================================================
  const adRecords = [
    { spotName: "header-banner", adType: "image", adImageUrl: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1200&h=120&fit=crop", clickUrl: "#", locale: "en", isActive: true },
    { spotName: "content-inline", adType: "image", adImageUrl: "https://images.unsplash.com/photo-1449824913935-59a10b8d2000?w=800&h=200&fit=crop", clickUrl: "#", locale: "en", isActive: true },
  ];

  await prisma.adSpot.createMany({ data: adRecords });
  console.log(`✅ ${adRecords.length} ads created`);

  // ============================================================
  // EVENTS
  // ============================================================
  const eventRecords = [
    // EN
    { title: "Manchester City vs Arsenal — Premier League", slug: "city-vs-arsenal-pl", description: "A crucial Premier League clash at the Etihad Stadium. Two title contenders go head-to-head in what promises to be one of the matches of the season.", eventImage: "https://images.unsplash.com/photo-1522778119026-d647f0596c20?w=800&h=450&fit=crop", venue: "Etihad Stadium", eventDate: new Date("2026-04-05T15:00:00Z"), ticketUrl: "https://mancity.com/tickets", priceRange: "£45 — £120", category: "sport", locale: "en", isFeatured: true },
    { title: "Manchester International Festival 2026", slug: "manchester-international-festival-2026", description: "The city's premier arts and culture festival returns with world-class performances, immersive installations, and thought-provoking exhibitions.", eventImage: "https://images.unsplash.com/photo-1501281668745-f7f57925c3b4?w=800&h=450&fit=crop", venue: "Various Venues", eventDate: new Date("2026-06-15T10:00:00Z"), eventEnd: new Date("2026-07-06T23:00:00Z"), ticketUrl: "https://mif.co.uk", priceRange: "Free — £50", category: "culture", locale: "en", isFeatured: true },
    { title: "Northern Quarter Art Walk", slug: "northern-quarter-art-walk", description: "A self-guided tour through the vibrant street art and galleries of Manchester's creative quarter.", eventImage: "https://images.unsplash.com/photo-1515542622106-78bda8ba0e5b?w=800&h=450&fit=crop", venue: "Northern Quarter", eventDate: new Date("2026-04-12T11:00:00Z"), category: "culture", locale: "en", isFeatured: false },
    { title: "Etihad Stadium Tour", slug: "etihad-stadium-tour", description: "Go behind the scenes of one of the most modern stadiums in world football. Visit the dressing rooms, walk through the tunnel, and sit in the dugout.", eventImage: "https://images.unsplash.com/photo-1577223625816-7546f13df25d?w=800&h=450&fit=crop", venue: "Etihad Stadium", eventDate: new Date("2026-03-20T10:00:00Z"), ticketUrl: "https://mancity.com/tours", priceRange: "£25", category: "sport", locale: "en", isFeatured: true },
    { title: "Manchester Food & Drink Festival", slug: "food-drink-festival-2026", description: "Celebrating the best of Manchester's incredible food scene with pop-ups, tastings, and masterclasses from top chefs.", eventImage: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800&h=450&fit=crop", venue: "Albert Square", eventDate: new Date("2026-05-10T12:00:00Z"), eventEnd: new Date("2026-05-20T22:00:00Z"), priceRange: "Free entry", category: "food", locale: "en", isFeatured: true },
    { title: "Co-op Live: Summer Concert Series", slug: "coop-live-summer-concerts", description: "Manchester's newest arena hosts an incredible lineup of international artists throughout the summer.", eventImage: "https://images.unsplash.com/photo-1501281668745-f7f57925c3b4?w=800&h=450&fit=crop", venue: "Co-op Live", eventDate: new Date("2026-06-01T19:00:00Z"), eventEnd: new Date("2026-08-31T23:00:00Z"), ticketUrl: "https://cooplive.com", priceRange: "£35 — £150", category: "music", locale: "en", isFeatured: true },

    // AR
    { title: "مانشستر سيتي ضد آرسنال — الدوري الإنجليزي", slug: "city-vs-arsenal-pl", description: "مواجهة حاسمة في الدوري الإنجليزي على ملعب الاتحاد بين اثنين من المتنافسين على اللقب.", eventImage: "https://images.unsplash.com/photo-1522778119026-d647f0596c20?w=800&h=450&fit=crop", venue: "ملعب الاتحاد", eventDate: new Date("2026-04-05T15:00:00Z"), ticketUrl: "https://mancity.com/tickets", priceRange: "£45 — £120", category: "sport", locale: "ar", isFeatured: true },
    { title: "مهرجان مانشستر الدولي 2026", slug: "manchester-international-festival-2026", description: "يعود مهرجان الفنون والثقافة الأول في المدينة مع عروض عالمية.", eventImage: "https://images.unsplash.com/photo-1501281668745-f7f57925c3b4?w=800&h=450&fit=crop", venue: "أماكن متعددة", eventDate: new Date("2026-06-15T10:00:00Z"), eventEnd: new Date("2026-07-06T23:00:00Z"), priceRange: "مجاني — £50", category: "culture", locale: "ar", isFeatured: true },
    { title: "جولة ملعب الاتحاد", slug: "etihad-stadium-tour", description: "اذهب وراء الكواليس في واحد من أكثر الملاعب حداثة في العالم.", eventImage: "https://images.unsplash.com/photo-1577223625816-7546f13df25d?w=800&h=450&fit=crop", venue: "ملعب الاتحاد", eventDate: new Date("2026-03-20T10:00:00Z"), ticketUrl: "https://mancity.com/tours", priceRange: "£25", category: "sport", locale: "ar", isFeatured: true },

    // HE
    { title: "מנצ'סטר סיטי נגד ארסנל — פרמייר ליג", slug: "city-vs-arsenal-pl", description: "עימות מכריע בפרמייר ליג באצטדיון איתיחאד בין שני מתחרים על התואר.", eventImage: "https://images.unsplash.com/photo-1522778119026-d647f0596c20?w=800&h=450&fit=crop", venue: "אצטדיון איתיחאד", eventDate: new Date("2026-04-05T15:00:00Z"), ticketUrl: "https://mancity.com/tickets", priceRange: "£45 — £120", category: "sport", locale: "he", isFeatured: true },
    { title: "פסטיבל מנצ'סטר הבינלאומי 2026", slug: "manchester-international-festival-2026", description: "פסטיבל האמנות והתרבות המוביל של העיר חוזר עם מופעים ברמה עולמית.", eventImage: "https://images.unsplash.com/photo-1501281668745-f7f57925c3b4?w=800&h=450&fit=crop", venue: "מקומות שונים", eventDate: new Date("2026-06-15T10:00:00Z"), eventEnd: new Date("2026-07-06T23:00:00Z"), priceRange: "חינם — £50", category: "culture", locale: "he", isFeatured: true },
    { title: "סיור באצטדיון איתיחאד", slug: "etihad-stadium-tour", description: "היכנסו מאחורי הקלעים של אחד האצטדיונים המודרניים ביותר בכדורגל העולמי.", eventImage: "https://images.unsplash.com/photo-1577223625816-7546f13df25d?w=800&h=450&fit=crop", venue: "אצטדיון איתיחאד", eventDate: new Date("2026-03-20T10:00:00Z"), ticketUrl: "https://mancity.com/tours", priceRange: "£25", category: "sport", locale: "he", isFeatured: true },

    // ES
    { title: "Manchester City vs Arsenal — Premier League", slug: "city-vs-arsenal-pl", description: "Un choque crucial de la Premier League en el Estadio Etihad entre dos aspirantes al título.", eventImage: "https://images.unsplash.com/photo-1522778119026-d647f0596c20?w=800&h=450&fit=crop", venue: "Estadio Etihad", eventDate: new Date("2026-04-05T15:00:00Z"), ticketUrl: "https://mancity.com/tickets", priceRange: "£45 — £120", category: "sport", locale: "es", isFeatured: true },
    { title: "Festival Internacional de Manchester 2026", slug: "manchester-international-festival-2026", description: "El principal festival de artes y cultura de la ciudad regresa con actuaciones de clase mundial.", eventImage: "https://images.unsplash.com/photo-1501281668745-f7f57925c3b4?w=800&h=450&fit=crop", venue: "Varios lugares", eventDate: new Date("2026-06-15T10:00:00Z"), eventEnd: new Date("2026-07-06T23:00:00Z"), priceRange: "Gratis — £50", category: "culture", locale: "es", isFeatured: true },
    { title: "Tour del Estadio Etihad", slug: "etihad-stadium-tour", description: "Ve detrás de escena en uno de los estadios más modernos del fútbol mundial.", eventImage: "https://images.unsplash.com/photo-1577223625816-7546f13df25d?w=800&h=450&fit=crop", venue: "Estadio Etihad", eventDate: new Date("2026-03-20T10:00:00Z"), ticketUrl: "https://mancity.com/tours", priceRange: "£25", category: "sport", locale: "es", isFeatured: true },
  ];

  await prisma.event.createMany({ data: eventRecords });
  console.log(`✅ ${eventRecords.length} events created`);

  console.log("🎉 Seed complete!");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
