services:
  - type: web
    name: mcity
    runtime: node
    rootDir: apps/web
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20.19.4
      - key: TURSO_DATABASE_URL
        sync: false
      - key: TURSO_AUTH_TOKEN
        sync: false
      - key: NEXT_PUBLIC_GA_ID
        sync: false
      - key: NEXT_PUBLIC_META_PIXEL_ID
        sync: false
    autoDeploy: true
