import type { NewsArticle, ProductShowcase, AdSpot } from "./types";

export const mockNews: NewsArticle[] = [
  {
    id: 1,
    title: "Manchester City Prepares for Champions League Quarter-Final",
    slug: "city-champions-league-quarter-final",
    excerpt: "The sky blues gear up for a crucial European clash as they aim to defend their title.",
    content_body: "Manchester City are preparing for their Champions League quarter-final match...",
    featured_image: "https://images.unsplash.com/photo-1522778119026-d647f0596c20?w=800&h=450&fit=crop",
    source_name: "BBC Sport",
    source_url: "https://bbc.co.uk/sport",
    published_at: "2026-03-14T10:00:00Z",
    locale: "en",
  },
  {
    id: 2,
    title: "New Etihad Campus Expansion Announced",
    slug: "etihad-campus-expansion",
    excerpt: "A major development project will transform the area surrounding the Etihad Stadium.",
    content_body: "City Football Group has announced plans to expand the Etihad Campus...",
    featured_image: "https://images.unsplash.com/photo-1577223625816-7546f13df25d?w=800&h=450&fit=crop",
    source_name: "Manchester Evening News",
    source_url: "https://manchestereveningnews.co.uk",
    published_at: "2026-03-13T14:30:00Z",
    locale: "en",
  },
  {
    id: 3,
    title: "Manchester's Northern Quarter: A Cultural Renaissance",
    slug: "northern-quarter-cultural-renaissance",
    excerpt: "How Manchester's creative heartbeat continues to shape the city's identity.",
    content_body: "The Northern Quarter has long been the cultural heart of Manchester...",
    featured_image: "https://images.unsplash.com/photo-1515542622106-78bda8ba0e5b?w=800&h=450&fit=crop",
    source_name: "The Guardian",
    source_url: "https://theguardian.com",
    published_at: "2026-03-12T09:15:00Z",
    locale: "en",
  },
  {
    id: 4,
    title: "Premier League Title Race Heats Up",
    slug: "premier-league-title-race",
    excerpt: "With just weeks remaining, every point counts in the most competitive season in years.",
    content_body: "The Premier League title race is reaching a fever pitch as teams battle...",
    featured_image: "https://images.unsplash.com/photo-1431324155629-1a6deb1dec8d?w=800&h=450&fit=crop",
    source_name: "Sky Sports",
    source_url: "https://skysports.com",
    published_at: "2026-03-11T16:00:00Z",
    locale: "en",
  },
  {
    id: 5,
    title: "Best Matchday Dining Spots Near Etihad Stadium",
    slug: "matchday-dining-etihad",
    excerpt: "From local favourites to hidden gems — where to eat before the big match.",
    content_body: "Whether you're looking for a quick bite or a proper sit-down meal...",
    featured_image: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800&h=450&fit=crop",
    source_name: "Time Out Manchester",
    source_url: "https://timeout.com/manchester",
    published_at: "2026-03-10T11:00:00Z",
    locale: "en",
  },
  {
    id: 6,
    title: "Youth Academy Star Signs Professional Contract",
    slug: "youth-academy-star-contract",
    excerpt: "Another product of the world-class academy system earns their first professional deal.",
    content_body: "Manchester City's academy continues to produce top-level talent...",
    featured_image: "https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=800&h=450&fit=crop",
    source_name: "City Xtra",
    source_url: "https://cityxtra.com",
    published_at: "2026-03-09T08:45:00Z",
    locale: "en",
  },
];

export const mockProducts: ProductShowcase[] = [
  {
    id: 1,
    product_name: "Manchester Skyline Premium Print",
    product_slug: "manchester-skyline-print",
    product_image: "https://images.unsplash.com/photo-1605034313761-73ea4a0cfbf3?w=400&h=400&fit=crop",
    description_short: "Stunning high-quality print of the Manchester skyline. Perfect for any fan's wall.",
    price_display: "£29.99",
    affiliate_link: "#",
    partner_name: "Amazon UK",
    locale: "en",
  },
  {
    id: 2,
    product_name: "Sky Blue Heritage Scarf",
    product_slug: "sky-blue-heritage-scarf",
    product_image: "https://images.unsplash.com/photo-1520903920243-00d872a2d1c9?w=400&h=400&fit=crop",
    description_short: "Classic sky blue and white scarf. Show your city colours with pride.",
    price_display: "£19.99",
    affiliate_link: "#",
    partner_name: "Fanatics",
    locale: "en",
  },
  {
    id: 3,
    product_name: "Manchester City Guide Book",
    product_slug: "city-guide-book",
    product_image: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400&h=400&fit=crop",
    description_short: "The definitive guide to Manchester — culture, food, history, and football.",
    price_display: "£14.99",
    affiliate_link: "#",
    partner_name: "Amazon UK",
    locale: "en",
  },
  {
    id: 4,
    product_name: "Football Culture Magazine Subscription",
    product_slug: "football-culture-magazine",
    product_image: "https://images.unsplash.com/photo-1526666923127-b2970f64b422?w=400&h=400&fit=crop",
    description_short: "Monthly magazine covering football culture, fashion, and fan stories.",
    price_display: "£9.99/mo",
    affiliate_link: "#",
    partner_name: "Press Partner",
    locale: "en",
  },
];

export const mockAds: AdSpot[] = [
  {
    id: 1,
    spot_name: "header-banner",
    ad_type: "image",
    ad_image_url: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1200&h=120&fit=crop",
    click_url: "#",
    locale: "en",
    is_active: true,
  },
  {
    id: 2,
    spot_name: "content-inline",
    ad_type: "image",
    ad_image_url: "https://images.unsplash.com/photo-1449824913935-59a10b8d2000?w=800&h=200&fit=crop",
    click_url: "#",
    locale: "en",
    is_active: true,
  },
];
