import type { NewsArticle, ProductShowcase, AdSpot } from "./types";
import type { Locale } from "./i18n/config";

// ============================================================
// NEWS — Multi-lingual
// ============================================================

const newsData: Record<Locale, NewsArticle[]> = {
  en: [
    {
      id: 1,
      title: "Manchester City Prepares for Champions League Quarter-Final",
      slug: "city-champions-league-quarter-final",
      excerpt: "The sky blues gear up for a crucial European clash as they aim to defend their title.",
      content_body: "Manchester City are preparing for their Champions League quarter-final match. The team has been training intensively at the Etihad Campus, with key players returning from injury.",
      featured_image: "https://images.unsplash.com/photo-1522778119026-d647f0596c20?w=800&h=450&fit=crop",
      source_name: "BBC Sport",
      source_url: "https://bbc.co.uk/sport",
      published_at: "2026-03-14T10:00:00Z",
      locale: "en",
    },
    {
      id: 2,
      title: "New Etihad Campus Expansion Announced",
      slug: "etihad-campus-expansion",
      excerpt: "A major development project will transform the area surrounding the Etihad Stadium.",
      content_body: "City Football Group has announced plans to expand the Etihad Campus with new training facilities and community spaces.",
      featured_image: "https://images.unsplash.com/photo-1577223625816-7546f13df25d?w=800&h=450&fit=crop",
      source_name: "Manchester Evening News",
      source_url: "https://manchestereveningnews.co.uk",
      published_at: "2026-03-13T14:30:00Z",
      locale: "en",
    },
    {
      id: 3,
      title: "Manchester's Northern Quarter: A Cultural Renaissance",
      slug: "northern-quarter-cultural-renaissance",
      excerpt: "How Manchester's creative heartbeat continues to shape the city's identity.",
      content_body: "The Northern Quarter has long been the cultural heart of Manchester, with its independent shops, street art, and vibrant nightlife scene.",
      featured_image: "https://images.unsplash.com/photo-1515542622106-78bda8ba0e5b?w=800&h=450&fit=crop",
      source_name: "The Guardian",
      source_url: "https://theguardian.com",
      published_at: "2026-03-12T09:15:00Z",
      locale: "en",
    },
    {
      id: 4,
      title: "Premier League Title Race Heats Up",
      slug: "premier-league-title-race",
      excerpt: "With just weeks remaining, every point counts in the most competitive season in years.",
      content_body: "The Premier League title race is reaching a fever pitch as teams battle for the coveted trophy.",
      featured_image: "https://images.unsplash.com/photo-1431324155629-1a6deb1dec8d?w=800&h=450&fit=crop",
      source_name: "Sky Sports",
      source_url: "https://skysports.com",
      published_at: "2026-03-11T16:00:00Z",
      locale: "en",
    },
    {
      id: 5,
      title: "Best Matchday Dining Spots Near Etihad Stadium",
      slug: "matchday-dining-etihad",
      excerpt: "From local favourites to hidden gems — where to eat before the big match.",
      content_body: "Whether you're looking for a quick bite or a proper sit-down meal before the game.",
      featured_image: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800&h=450&fit=crop",
      source_name: "Time Out Manchester",
      source_url: "https://timeout.com/manchester",
      published_at: "2026-03-10T11:00:00Z",
      locale: "en",
    },
    {
      id: 6,
      title: "Youth Academy Star Signs Professional Contract",
      slug: "youth-academy-star-contract",
      excerpt: "Another product of the world-class academy system earns their first professional deal.",
      content_body: "Manchester City's academy continues to produce top-level talent with another graduate signing a professional contract.",
      featured_image: "https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=800&h=450&fit=crop",
      source_name: "City Xtra",
      source_url: "https://cityxtra.com",
      published_at: "2026-03-09T08:45:00Z",
      locale: "en",
    },
  ],
  ar: [
    {
      id: 101,
      title: "مانشستر سيتي يستعد لربع نهائي دوري أبطال أوروبا",
      slug: "city-champions-league-quarter-final",
      excerpt: "السماويون يستعدون لمواجهة أوروبية حاسمة في سعيهم للدفاع عن لقبهم.",
      content_body: "يستعد مانشستر سيتي لمباراة ربع نهائي دوري أبطال أوروبا. وقد كان الفريق يتدرب بشكل مكثف في أكاديمية الاتحاد.",
      featured_image: "https://images.unsplash.com/photo-1522778119026-d647f0596c20?w=800&h=450&fit=crop",
      source_name: "بي بي سي سبورت",
      source_url: "https://bbc.co.uk/sport",
      published_at: "2026-03-14T10:00:00Z",
      locale: "ar",
    },
    {
      id: 102,
      title: "الإعلان عن توسعة جديدة لمجمع الاتحاد",
      slug: "etihad-campus-expansion",
      excerpt: "مشروع تطوير كبير سيحول المنطقة المحيطة بملعب الاتحاد.",
      content_body: "أعلنت مجموعة سيتي فوتبول عن خطط لتوسيع مجمع الاتحاد بمرافق تدريب جديدة.",
      featured_image: "https://images.unsplash.com/photo-1577223625816-7546f13df25d?w=800&h=450&fit=crop",
      source_name: "مانشستر إيفنينغ نيوز",
      source_url: "https://manchestereveningnews.co.uk",
      published_at: "2026-03-13T14:30:00Z",
      locale: "ar",
    },
    {
      id: 103,
      title: "الحي الشمالي في مانشستر: نهضة ثقافية",
      slug: "northern-quarter-cultural-renaissance",
      excerpt: "كيف يستمر قلب مانشستر الإبداعي في تشكيل هوية المدينة.",
      content_body: "لطالما كان الحي الشمالي القلب الثقافي لمانشستر بمحلاته المستقلة وفنون الشارع.",
      featured_image: "https://images.unsplash.com/photo-1515542622106-78bda8ba0e5b?w=800&h=450&fit=crop",
      source_name: "الغارديان",
      source_url: "https://theguardian.com",
      published_at: "2026-03-12T09:15:00Z",
      locale: "ar",
    },
    {
      id: 104,
      title: "سباق لقب الدوري الإنجليزي يحتدم",
      slug: "premier-league-title-race",
      excerpt: "مع بقاء أسابيع قليلة، كل نقطة مهمة في أكثر المواسم تنافسية منذ سنوات.",
      content_body: "يصل سباق لقب الدوري الإنجليزي الممتاز إلى ذروته مع تنافس الفرق على الكأس المرغوبة.",
      featured_image: "https://images.unsplash.com/photo-1431324155629-1a6deb1dec8d?w=800&h=450&fit=crop",
      source_name: "سكاي سبورتس",
      source_url: "https://skysports.com",
      published_at: "2026-03-11T16:00:00Z",
      locale: "ar",
    },
    {
      id: 105,
      title: "أفضل أماكن تناول الطعام بالقرب من ملعب الاتحاد",
      slug: "matchday-dining-etihad",
      excerpt: "من المفضلات المحلية إلى الجواهر المخفية — أين تأكل قبل المباراة الكبيرة.",
      content_body: "سواء كنت تبحث عن وجبة سريعة أو عشاء مناسب قبل المباراة.",
      featured_image: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800&h=450&fit=crop",
      source_name: "تايم آوت مانشستر",
      source_url: "https://timeout.com/manchester",
      published_at: "2026-03-10T11:00:00Z",
      locale: "ar",
    },
    {
      id: 106,
      title: "نجم الأكاديمية الشاب يوقع عقداً احترافياً",
      slug: "youth-academy-star-contract",
      excerpt: "منتج آخر من نظام الأكاديمية العالمي يحصل على أول عقد احترافي له.",
      content_body: "تواصل أكاديمية مانشستر سيتي إنتاج مواهب من الدرجة الأولى.",
      featured_image: "https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=800&h=450&fit=crop",
      source_name: "سيتي إكسترا",
      source_url: "https://cityxtra.com",
      published_at: "2026-03-09T08:45:00Z",
      locale: "ar",
    },
  ],
  he: [
    {
      id: 201,
      title: "מנצ'סטר סיטי נערכת לרבע גמר ליגת האלופות",
      slug: "city-champions-league-quarter-final",
      excerpt: "הכחולים נערכים לעימות אירופי מכריע במטרה להגן על התואר שלהם.",
      content_body: "מנצ'סטר סיטי נערכת למשחק רבע הגמר בליגת האלופות. הקבוצה התאמנה באינטנסיביות.",
      featured_image: "https://images.unsplash.com/photo-1522778119026-d647f0596c20?w=800&h=450&fit=crop",
      source_name: "BBC Sport",
      source_url: "https://bbc.co.uk/sport",
      published_at: "2026-03-14T10:00:00Z",
      locale: "he",
    },
    {
      id: 202,
      title: "הוכרזה הרחבה חדשה של קמפוס איתיחאד",
      slug: "etihad-campus-expansion",
      excerpt: "פרויקט פיתוח גדול ישנה את האזור שמסביב לאצטדיון איתיחאד.",
      content_body: "קבוצת סיטי פוטבול הכריזה על תוכניות להרחבת קמפוס איתיחאד עם מתקני אימון חדשים.",
      featured_image: "https://images.unsplash.com/photo-1577223625816-7546f13df25d?w=800&h=450&fit=crop",
      source_name: "Manchester Evening News",
      source_url: "https://manchestereveningnews.co.uk",
      published_at: "2026-03-13T14:30:00Z",
      locale: "he",
    },
    {
      id: 203,
      title: "הרובע הצפוני של מנצ'סטר: רנסנס תרבותי",
      slug: "northern-quarter-cultural-renaissance",
      excerpt: "כיצד הלב היצירתי של מנצ'סטר ממשיך לעצב את זהות העיר.",
      content_body: "הרובע הצפוני היה מאז ומתמיד הלב התרבותי של מנצ'סטר.",
      featured_image: "https://images.unsplash.com/photo-1515542622106-78bda8ba0e5b?w=800&h=450&fit=crop",
      source_name: "The Guardian",
      source_url: "https://theguardian.com",
      published_at: "2026-03-12T09:15:00Z",
      locale: "he",
    },
    {
      id: 204,
      title: "מירוץ האליפות בפרמייר ליג מתחמם",
      slug: "premier-league-title-race",
      excerpt: "עם שבועות ספורים שנותרו, כל נקודה חשובה בעונה התחרותית ביותר מזה שנים.",
      content_body: "מירוץ האליפות בפרמייר ליג מגיע לשיאו כאשר קבוצות נלחמות על הגביע.",
      featured_image: "https://images.unsplash.com/photo-1431324155629-1a6deb1dec8d?w=800&h=450&fit=crop",
      source_name: "Sky Sports",
      source_url: "https://skysports.com",
      published_at: "2026-03-11T16:00:00Z",
      locale: "he",
    },
    {
      id: 205,
      title: "מקומות האוכל הטובים ביותר ליד אצטדיון איתיחאד",
      slug: "matchday-dining-etihad",
      excerpt: "מהמועדפים המקומיים ועד לפנינים נסתרות — איפה לאכול לפני המשחק הגדול.",
      content_body: "בין אם אתם מחפשים ביס מהיר או ארוחה מסודרת לפני המשחק.",
      featured_image: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800&h=450&fit=crop",
      source_name: "Time Out Manchester",
      source_url: "https://timeout.com/manchester",
      published_at: "2026-03-10T11:00:00Z",
      locale: "he",
    },
    {
      id: 206,
      title: "כוכב האקדמיה הצעיר חותם על חוזה מקצועי",
      slug: "youth-academy-star-contract",
      excerpt: "עוד תוצר של מערכת האקדמיה ברמה עולמית מרוויח את החוזה המקצועי הראשון שלו.",
      content_body: "האקדמיה של מנצ'סטר סיטי ממשיכה לייצר כישרונות ברמה הגבוהה ביותר.",
      featured_image: "https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=800&h=450&fit=crop",
      source_name: "City Xtra",
      source_url: "https://cityxtra.com",
      published_at: "2026-03-09T08:45:00Z",
      locale: "he",
    },
  ],
  es: [
    {
      id: 301,
      title: "Manchester City se prepara para los cuartos de final de la Champions League",
      slug: "city-champions-league-quarter-final",
      excerpt: "Los celestes se preparan para un enfrentamiento europeo crucial en su defensa del título.",
      content_body: "El Manchester City se está preparando para su partido de cuartos de final de la Liga de Campeones.",
      featured_image: "https://images.unsplash.com/photo-1522778119026-d647f0596c20?w=800&h=450&fit=crop",
      source_name: "BBC Sport",
      source_url: "https://bbc.co.uk/sport",
      published_at: "2026-03-14T10:00:00Z",
      locale: "es",
    },
    {
      id: 302,
      title: "Anunciada la nueva expansión del Campus Etihad",
      slug: "etihad-campus-expansion",
      excerpt: "Un importante proyecto de desarrollo transformará la zona que rodea el Estadio Etihad.",
      content_body: "City Football Group ha anunciado planes para ampliar el Campus Etihad con nuevas instalaciones.",
      featured_image: "https://images.unsplash.com/photo-1577223625816-7546f13df25d?w=800&h=450&fit=crop",
      source_name: "Manchester Evening News",
      source_url: "https://manchestereveningnews.co.uk",
      published_at: "2026-03-13T14:30:00Z",
      locale: "es",
    },
    {
      id: 303,
      title: "El Northern Quarter de Manchester: un renacimiento cultural",
      slug: "northern-quarter-cultural-renaissance",
      excerpt: "Cómo el corazón creativo de Manchester sigue dando forma a la identidad de la ciudad.",
      content_body: "El Northern Quarter ha sido durante mucho tiempo el corazón cultural de Manchester.",
      featured_image: "https://images.unsplash.com/photo-1515542622106-78bda8ba0e5b?w=800&h=450&fit=crop",
      source_name: "The Guardian",
      source_url: "https://theguardian.com",
      published_at: "2026-03-12T09:15:00Z",
      locale: "es",
    },
    {
      id: 304,
      title: "La carrera por el título de la Premier League se intensifica",
      slug: "premier-league-title-race",
      excerpt: "Con pocas semanas restantes, cada punto cuenta en la temporada más competitiva en años.",
      content_body: "La carrera por el título de la Premier League está alcanzando su punto álgido.",
      featured_image: "https://images.unsplash.com/photo-1431324155629-1a6deb1dec8d?w=800&h=450&fit=crop",
      source_name: "Sky Sports",
      source_url: "https://skysports.com",
      published_at: "2026-03-11T16:00:00Z",
      locale: "es",
    },
    {
      id: 305,
      title: "Los mejores restaurantes cerca del Estadio Etihad",
      slug: "matchday-dining-etihad",
      excerpt: "Desde los favoritos locales hasta joyas ocultas: dónde comer antes del gran partido.",
      content_body: "Ya sea que busques un bocado rápido o una comida adecuada antes del partido.",
      featured_image: "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800&h=450&fit=crop",
      source_name: "Time Out Manchester",
      source_url: "https://timeout.com/manchester",
      published_at: "2026-03-10T11:00:00Z",
      locale: "es",
    },
    {
      id: 306,
      title: "Estrella juvenil firma contrato profesional",
      slug: "youth-academy-star-contract",
      excerpt: "Otro producto del sistema de academia de clase mundial consigue su primer contrato profesional.",
      content_body: "La academia del Manchester City sigue produciendo talento de primer nivel.",
      featured_image: "https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=800&h=450&fit=crop",
      source_name: "City Xtra",
      source_url: "https://cityxtra.com",
      published_at: "2026-03-09T08:45:00Z",
      locale: "es",
    },
  ],
};

// ============================================================
// PRODUCTS — Multi-lingual
// ============================================================

const productsData: Record<Locale, ProductShowcase[]> = {
  en: [
    {
      id: 1,
      product_name: "Manchester Skyline Premium Print",
      product_slug: "manchester-skyline-print",
      product_image: "https://images.unsplash.com/photo-1605034313761-73ea4a0cfbf3?w=400&h=400&fit=crop",
      description_short: "Stunning high-quality print of the Manchester skyline. Perfect for any fan's wall.",
      price_display: "£29.99",
      affiliate_link: "#",
      partner_name: "Amazon UK",
      locale: "en",
    },
    {
      id: 2,
      product_name: "Sky Blue Heritage Scarf",
      product_slug: "sky-blue-heritage-scarf",
      product_image: "https://images.unsplash.com/photo-1520903920243-00d872a2d1c9?w=400&h=400&fit=crop",
      description_short: "Classic sky blue and white scarf. Show your city colours with pride.",
      price_display: "£19.99",
      affiliate_link: "#",
      partner_name: "Fanatics",
      locale: "en",
    },
    {
      id: 3,
      product_name: "Manchester City Guide Book",
      product_slug: "city-guide-book",
      product_image: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400&h=400&fit=crop",
      description_short: "The definitive guide to Manchester — culture, food, history, and football.",
      price_display: "£14.99",
      affiliate_link: "#",
      partner_name: "Amazon UK",
      locale: "en",
    },
    {
      id: 4,
      product_name: "Football Culture Magazine",
      product_slug: "football-culture-magazine",
      product_image: "https://images.unsplash.com/photo-1526666923127-b2970f64b422?w=400&h=400&fit=crop",
      description_short: "Monthly magazine covering football culture, fashion, and fan stories.",
      price_display: "£9.99/mo",
      affiliate_link: "#",
      partner_name: "Press Partner",
      locale: "en",
    },
  ],
  ar: [
    {
      id: 101,
      product_name: "طباعة أفق مانشستر الفاخرة",
      product_slug: "manchester-skyline-print",
      product_image: "https://images.unsplash.com/photo-1605034313761-73ea4a0cfbf3?w=400&h=400&fit=crop",
      description_short: "طباعة عالية الجودة لأفق مانشستر. مثالية لجدار أي مشجع.",
      price_display: "£29.99",
      affiliate_link: "#",
      partner_name: "Amazon UK",
      locale: "ar",
    },
    {
      id: 102,
      product_name: "وشاح التراث الأزرق السماوي",
      product_slug: "sky-blue-heritage-scarf",
      product_image: "https://images.unsplash.com/photo-1520903920243-00d872a2d1c9?w=400&h=400&fit=crop",
      description_short: "وشاح كلاسيكي باللون الأزرق السماوي والأبيض. أظهر ألوان مدينتك بفخر.",
      price_display: "£19.99",
      affiliate_link: "#",
      partner_name: "Fanatics",
      locale: "ar",
    },
    {
      id: 103,
      product_name: "كتاب دليل مانشستر",
      product_slug: "city-guide-book",
      product_image: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400&h=400&fit=crop",
      description_short: "الدليل الشامل لمانشستر — الثقافة والطعام والتاريخ وكرة القدم.",
      price_display: "£14.99",
      affiliate_link: "#",
      partner_name: "Amazon UK",
      locale: "ar",
    },
    {
      id: 104,
      product_name: "مجلة ثقافة كرة القدم",
      product_slug: "football-culture-magazine",
      product_image: "https://images.unsplash.com/photo-1526666923127-b2970f64b422?w=400&h=400&fit=crop",
      description_short: "مجلة شهرية تغطي ثقافة كرة القدم والأزياء وقصص المشجعين.",
      price_display: "£9.99/شهرياً",
      affiliate_link: "#",
      partner_name: "Press Partner",
      locale: "ar",
    },
  ],
  he: [
    {
      id: 201,
      product_name: "הדפס פרימיום של קו הרקיע של מנצ'סטר",
      product_slug: "manchester-skyline-print",
      product_image: "https://images.unsplash.com/photo-1605034313761-73ea4a0cfbf3?w=400&h=400&fit=crop",
      description_short: "הדפס איכותי מדהים של קו הרקיע של מנצ'סטר. מושלם לקיר של כל אוהד.",
      price_display: "£29.99",
      affiliate_link: "#",
      partner_name: "Amazon UK",
      locale: "he",
    },
    {
      id: 202,
      product_name: "צעיף מורשת כחול שמיים",
      product_slug: "sky-blue-heritage-scarf",
      product_image: "https://images.unsplash.com/photo-1520903920243-00d872a2d1c9?w=400&h=400&fit=crop",
      description_short: "צעיף קלאסי בכחול שמיים ולבן. הציגו את צבעי העיר שלכם בגאווה.",
      price_display: "£19.99",
      affiliate_link: "#",
      partner_name: "Fanatics",
      locale: "he",
    },
    {
      id: 203,
      product_name: "ספר מדריך מנצ'סטר",
      product_slug: "city-guide-book",
      product_image: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400&h=400&fit=crop",
      description_short: "המדריך המוחלט למנצ'סטר — תרבות, אוכל, היסטוריה וכדורגל.",
      price_display: "£14.99",
      affiliate_link: "#",
      partner_name: "Amazon UK",
      locale: "he",
    },
    {
      id: 204,
      product_name: "מגזין תרבות כדורגל",
      product_slug: "football-culture-magazine",
      product_image: "https://images.unsplash.com/photo-1526666923127-b2970f64b422?w=400&h=400&fit=crop",
      description_short: "מגזין חודשי המכסה תרבות כדורגל, אופנה וסיפורי אוהדים.",
      price_display: "£9.99/חודש",
      affiliate_link: "#",
      partner_name: "Press Partner",
      locale: "he",
    },
  ],
  es: [
    {
      id: 301,
      product_name: "Impresión Premium del Horizonte de Manchester",
      product_slug: "manchester-skyline-print",
      product_image: "https://images.unsplash.com/photo-1605034313761-73ea4a0cfbf3?w=400&h=400&fit=crop",
      description_short: "Impresión de alta calidad del horizonte de Manchester. Perfecta para la pared de cualquier aficionado.",
      price_display: "£29.99",
      affiliate_link: "#",
      partner_name: "Amazon UK",
      locale: "es",
    },
    {
      id: 302,
      product_name: "Bufanda Heritage Azul Cielo",
      product_slug: "sky-blue-heritage-scarf",
      product_image: "https://images.unsplash.com/photo-1520903920243-00d872a2d1c9?w=400&h=400&fit=crop",
      description_short: "Bufanda clásica en azul cielo y blanco. Muestra los colores de tu ciudad con orgullo.",
      price_display: "£19.99",
      affiliate_link: "#",
      partner_name: "Fanatics",
      locale: "es",
    },
    {
      id: 303,
      product_name: "Libro Guía de Manchester",
      product_slug: "city-guide-book",
      product_image: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400&h=400&fit=crop",
      description_short: "La guía definitiva de Manchester: cultura, gastronomía, historia y fútbol.",
      price_display: "£14.99",
      affiliate_link: "#",
      partner_name: "Amazon UK",
      locale: "es",
    },
    {
      id: 304,
      product_name: "Revista Cultura del Fútbol",
      product_slug: "football-culture-magazine",
      product_image: "https://images.unsplash.com/photo-1526666923127-b2970f64b422?w=400&h=400&fit=crop",
      description_short: "Revista mensual sobre cultura futbolística, moda e historias de aficionados.",
      price_display: "£9.99/mes",
      affiliate_link: "#",
      partner_name: "Press Partner",
      locale: "es",
    },
  ],
};

// ============================================================
// ADS
// ============================================================

export const mockAds: AdSpot[] = [
  {
    id: 1,
    spot_name: "header-banner",
    ad_type: "image",
    ad_image_url: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=1200&h=120&fit=crop",
    click_url: "#",
    locale: "en",
    is_active: true,
  },
  {
    id: 2,
    spot_name: "content-inline",
    ad_type: "image",
    ad_image_url: "https://images.unsplash.com/photo-1449824913935-59a10b8d2000?w=800&h=200&fit=crop",
    click_url: "#",
    locale: "en",
    is_active: true,
  },
];

// ============================================================
// Accessor functions — locale-aware
// ============================================================

export function getNews(locale: Locale): NewsArticle[] {
  return newsData[locale] || newsData.en;
}

export function getProducts(locale: Locale): ProductShowcase[] {
  return productsData[locale] || productsData.en;
}
